# Generated by Django 5.0.6 on 2024-06-12 07:16

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='image',
            field=models.ImageField(null=True, upload_to=airport.models.airplane_image_file_path),
        ),
    ]
